apiVersion: apps/v1
kind: Deployment
metadata:
  name: iykra-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iykra-db
  template:
    metadata:
      labels:
        app: iykra-db
    spec:
      containers:
        - name: iykra-db-container
          image: iykra_db:latest
          imagePullPolicy: Never   # Prevent pulling from a registry
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_HOST
              value: "iykra-db-service"
            - name: DB_PORT
              value: "5432"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data  # Default PostgreSQL data directory
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: iykra-pvc