apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iykra-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage  # Ensure this matches the PV's storage class