apiVersion: v1
kind: Service
metadata:
  name: iykra-app-service
spec:
  type: LoadBalancer  # Expose the app outside the cluster
  selector:
    app: iykra-app
  ports:
    - port: 3000
      targetPort: 8080
      protocol: TCP
      name: http